name 'webapp-linux'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures webapp-linux'
long_description 'Installs/Configures webapp-linux'
version '0.1.13'

depends 'apt', '~> 2.9.2'
depends 'httpd', '~> 0.3.3'
depends 'firewall', '~> 2.3.0'
